### ISSUE TITLE
Phabricator prefix for interwiki links doesn't work

### ISSUE THREAD

**Issue by samwilson** [jhsoby/telegram-wikilinksbot#20]
Interwiki links such as `[[wikidata:Q42]]` work as expected, but ones like `[[phabricator:T123]]` don't.

**Comment by camelCaseNick** [comment]
Yes, indeed. Phabricator is not running MediaWiki and the URL in https://github.com/jhsoby/telegram-wikilinksbot/blob/1e0483ac32fc752df3fe4fea960cfd5ec0582778/wikilinksbot.py#L179 assumes otherwise.

Currently, you would need to write `T123` in a chat, the same way `Q42` works.
