### ISSUE TITLE
Tr.wikiquote

### ISSUE THREAD

**Issue by hsnozalpp** [jhsoby/telegram-wikilinksbot#32]
Bot could not figure out trwikiquote as a MediaWiki.

**Comment by jhsoby** [comment]
Hi @hsnozalpp, thanks for reporting! I just tested this with the command `/setwiki normallinks https://tr.wikiquote.org/`, and it works as it should, for me at least. Is that the command you tried? If not, what did you try (maybe I need to add a fix for it in the code)?

**Comment by hsnozalpp** [comment]
I wasn't actually the admin of the official Trwikiquote Telegram server so
I wasn't the one who tried but when I delivered this email to admins, they
said that it worked. Thank you for your support.

Jon Harald Søby ***@***.***>, 9 Ağu 2021 Pzt, 13:35 tarihinde
şunu yazdı:

**Comment by jhsoby** [comment]
Ah, yes, that explains it. Thanks!
