### ISSUE TITLE
Resolve Commons MIDs to file names

### ISSUE THREAD

**Issue by mahir256** [jhsoby/telegram-wikilinksbot#36]
While MIDs do presently link to the appropriate files on Commons, it will be very useful if filenames could be displayed alongside the wikilinksbot's output for a given MID, just as is similarly done for other types of entities. Thus M71106419 should return "Hello (yellow).svg" in addition to providing the appropriate entity link.

**Comment by jhsoby** [comment]
Hmm, I thought it already did that. I'll take a look!
