### ISSUE TITLE
Links with «» in them don't get linked

### ISSUE THREAD

**Issue by jhsoby** [jhsoby/telegram-wikilinksbot#40]
If I link a page like [[w:no:MS «Erkna»]], the bot returns unlinked text. Need to investigate.

**Comment by dpriskorn** [comment]
Hi. I learned something new thanks to this.
I did not know that # and other characters we okay not to quote 😀

**Comment by jhsoby** [comment]
Nice 😃
In this case it wouldn't make much of a difference – the links would work no matter if they were quoted or not, but if I hadn't exempted those characters, the URL preview (when you click a link and it shows which URL it will take you to) would show "%23" for "#" and "%3A" for ":", which I didn't want, since it's less readable. 😊
